services:
  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    container_name: delivery-service
    ports:
      - "8091:8080"
    environment:
      "SERVICE_PORT": 8080
      "DELIVERY_SERVICE_HOST": flower-shop-service:8080


  flower-shop-service:
    build:
      context: ./flower-shop-service
      dockerfile: Dockerfile
    container_name: flower-shop-service
    ports:
      - "8090:8080"
    environment:
      "SERVICE_PORT": 8080
      "DELIVERY_SERVICE_HOST": delivery-service:8080
