spring:
  application:
    name: flower-shop-service

rest:
  specifications:
    delivery-service:
      read-timeout: 3s

integration:
  delivery-service:
    host: http://localhost:8083
    api-key: my-secure-api-key
    create-delivery-path: /api/v1/deliveries
    delete-delivery-path: /api/v1/deliveries/{id}/cancel

server:
  port: 8084

resilience4j:
  retry:
    instances:
      delivery-service:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-max-wait-duration: 8s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException.TooManyRequests

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info