spring:
  application:
    name: delivery-service

rest:
  specifications:
    source-system-service:
      read-timeout: 3s

integration:
  flower-shop-service:
    host: localhost:8084
    api-key: my-secure-api-key

server:
  port: 8083

resilience4j:
  retry:
    instances:
      source-system-service:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-max-wait-duration: 8s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException.TooManyRequests

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info